# # PP + one axis
# MESH_PIPELINE=-1 MESH_DATA=2 MESH_FSDP=1 MESH_SEQ=1 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
# MESH_PIPELINE=-1 MESH_DATA=1 MESH_FSDP=2 MESH_SEQ=1 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
# MESH_PIPELINE=-1 MESH_DATA=1 MESH_FSDP=1 MESH_SEQ=2 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
# MESH_PIPELINE=-1 MESH_DATA=1 MESH_FSDP=1 MESH_SEQ=1 MESH_MODEL=2 MAX_STEP=3 bash launch_70B_single_node.sh

# # FSDP + one axis
# MESH_PIPELINE=2 MESH_DATA=1 MESH_FSDP=-1 MESH_SEQ=1 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
# MESH_PIPELINE=1 MESH_DATA=2 MESH_FSDP=-1 MESH_SEQ=1 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
# MESH_PIPELINE=1 MESH_DATA=1 MESH_FSDP=-1 MESH_SEQ=2 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
# MESH_PIPELINE=1 MESH_DATA=1 MESH_FSDP=-1 MESH_SEQ=1 MESH_MODEL=2 MAX_STEP=3 bash launch_70B_single_node.sh

# # TP + one axis
# MESH_PIPELINE=2 MESH_DATA=1 MESH_FSDP=1 MESH_SEQ=1 MESH_MODEL=-1 MAX_STEP=3 bash launch_70B_single_node.sh
# MESH_PIPELINE=1 MESH_DATA=2 MESH_FSDP=1 MESH_SEQ=1 MESH_MODEL=-1 MAX_STEP=3 bash launch_70B_single_node.sh
# MESH_PIPELINE=1 MESH_DATA=1 MESH_FSDP=2 MESH_SEQ=1 MESH_MODEL=-1 MAX_STEP=3 bash launch_70B_single_node.sh
# MESH_PIPELINE=1 MESH_DATA=1 MESH_FSDP=1 MESH_SEQ=2 MESH_MODEL=-1 MAX_STEP=3 bash launch_70B_single_node.sh

# 3 axes
MESH_PIPELINE=2 MESH_DATA=2 MESH_FSDP=2 MESH_SEQ=1 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
MESH_PIPELINE=2 MESH_DATA=2 MESH_FSDP=1 MESH_SEQ=2 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
MESH_PIPELINE=2 MESH_DATA=2 MESH_FSDP=1 MESH_SEQ=1 MESH_MODEL=2 MAX_STEP=3 bash launch_70B_single_node.sh
MESH_PIPELINE=2 MESH_DATA=1 MESH_FSDP=2 MESH_SEQ=2 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
MESH_PIPELINE=2 MESH_DATA=1 MESH_FSDP=2 MESH_SEQ=1 MESH_MODEL=2 MAX_STEP=3 bash launch_70B_single_node.sh
MESH_PIPELINE=2 MESH_DATA=1 MESH_FSDP=1 MESH_SEQ=2 MESH_MODEL=2 MAX_STEP=3 bash launch_70B_single_node.sh
MESH_PIPELINE=1 MESH_DATA=2 MESH_FSDP=2 MESH_SEQ=2 MESH_MODEL=1 MAX_STEP=3 bash launch_70B_single_node.sh
MESH_PIPELINE=1 MESH_DATA=2 MESH_FSDP=2 MESH_SEQ=1 MESH_MODEL=2 MAX_STEP=3 bash launch_70B_single_node.sh
MESH_PIPELINE=1 MESH_DATA=2 MESH_FSDP=1 MESH_SEQ=2 MESH_MODEL=2 MAX_STEP=3 bash launch_70B_single_node.sh
MESH_PIPELINE=1 MESH_DATA=1 MESH_FSDP=2 MESH_SEQ=2 MESH_MODEL=2 MAX_STEP=3 bash launch_70B_single_node.sh